font_family FiraCode Nerd Font

italic_font auto

bold_font auto

bold_italic_font auto

font_size 16.0

# tab_bar_style hidden

background_opacity 0.85

hide_window_decorations yes

enable_audio_bell no

url_style curly

shell zsh

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
