require("perfecto.plugins-setup")
require("perfecto.core.options")
require("perfecto.core.keymaps")
require("perfecto.core.colorscheme")
require("perfecto.plugins.appearance.nvim-tree")
require("perfecto.plugins.appearance.gitsigns")
require("perfecto.plugins.appearance.indent")
-- require("perfecto.plugins.appearance.discord")
require("perfecto.plugins.lsp.nvim-cmp")
require("perfecto.plugins.lsp.mason")
require("perfecto.plugins.lsp.lspsaga")
require("perfecto.plugins.lsp.lspconfig")
require("perfecto.plugins.lsp.conform")
require("perfecto.plugins.lsp.nvim-lint")
require("perfecto.plugins.lsp.treesitter")
require("perfecto.plugins.lsp.autopairs")
require("perfecto.plugins.productivity.telescope")
require("perfecto.plugins.productivity.comment")
require("perfecto.plugins.productivity.harpoon")
-- require("perfecto.plugins.productivity.sniprun")
require("perfecto.plugins.productivity.color")
require("perfecto.plugins.productivity.cpp")
